Platine/Controllers/ExperienceController.cs
using Platine.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Platine.Database.BusinessObject;
using Platine.Exceptions;

namespace Platine.Controllers
{
    [SessionExpire]
    public class ExperienceController : Controller
    {
        // GET: Experience
        public ActionResult Index()
        {
            Guid id = (Guid)Session["PlatineId"];
            return View(DataAccessAction.experience.GetExperienceByUserId(id));
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult AddExperience(Experience e)
        {
            
            Guid id = (Guid)Session["PlatineId"];
            e.UserId = id;
            DataAccessAction.experience.AddExperience(e);
            return Redirect("/Experience");
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                Guid userId = (Guid)Session["PlatineId"];
                DataAccessAction.experience.DeleteExperience(id, userId);

            }
            catch (PlatineException p)
            {
                ViewBag.Message = p.Message;
                
            }
            return Redirect("/Experience");
        }

        public ActionResult Detail(Guid id)
        {
            Experience e = null;
            try
            {
                Guid userId = (Guid)Session["PlatineId"];
                e = DataAccessAction.experience.GetExperienceById(id, userId);
                Console.WriteLine("");
            }
            catch (PlatineException p)
            {

                ViewBag.Message = p.Message;
                return Redirect("/Experience");
            }
            return View(e);
        }


    }
}

Platine/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Platine.Database.BusinessObject;
using Platine.Exceptions;
using Platine.Database;
using System.Net.Mail;
using Platine.Models;
using System.Text.RegularExpressions;

namespace Platine.Controllers
{

    public class UserController : Controller
    {
        [SessionExpire]
        public ActionResult Index()
        {
            Guid id = (Guid)Session["PlatineId"];
            return View(DataAccessAction.user.GetUserById(id));
        }

        public ActionResult RegisterPage()
        {
            return View();
        }

        public ActionResult Register(User u)
        {
            try
            {
                DataAccessAction.user.Register(u);
            }
            catch (UserException ue)
            {
                ViewBag.Message = ue.Message;
                return View("RegisterPage");
            }
            return Redirect("/");
        }

        [SessionExpire]
        public ActionResult EditPasswordPage()
        {
            return View();
        }

        [SessionExpire]
        public ActionResult EditPassword(NewPasswordModel newPasswordModel)
        {
            Guid id = (Guid)Session["PlatineId"];
            User u = DataAccessAction.user.GetUserById(id);
            Regex r = new Regex(@"\d+");
            if (!r.IsMatch(newPasswordModel.Password))
            {
                ViewBag.Message = "The password must contains a int";
                return View("EditPasswordPage");
            }
            u.Password = newPasswordModel.Password;
            DataAccessAction.user.UpdateUser(u);
            return Redirect("/User");
        }
        [SessionExpire]
        public ActionResult EditProfil()
        {
            Guid id = (Guid)Session["PlatineId"];
            return View(DataAccessAction.user.GetUserById(id));
        }

        public ActionResult SubmitEditProfil(User user)
        {
            try
            {
                DataAccessAction.user.UpdateUser(user);
            }
            catch (PlatineException p)
            {

                ViewBag.Error = p.Message;
            }
            return Redirect("/User");
        }

        public async System.Threading.Tasks.Task<ActionResult> SendMailAsync()
        {
            var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress("mohameddiallo93md@gmail.com")); //replace with valid value
            message.Subject = "Your email subject";
            message.Body = string.Format(body, "mohamed", "mo-2010@live.fr", "Password");
            message.IsBodyHtml = true;
            using (var smtp = new SmtpClient())
            {
                await smtp.SendMailAsync(message);
                return RedirectToAction("Sent");
            }
        }

        public ActionResult Logout()
        {
            Session["PlatineId"] = null;
            Session["PlatineLogin"] = null;
            return Redirect("/");
        }



    }
}

Platine/Views/User/EditPasswordPage.cshtml
@model Platine.Models.NewPasswordModel

@{
    ViewBag.Title = "EditPasswordPage";
}

<h2>EditPasswordPage</h2>
@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" role="alert">
        <strong>Oh snap!</strong> @ViewBag.Message.
    </div>
}

<form action="/User/EditPassword">

    <div class="form-group">

        <input type="password" class="form-control" name="Password" placeholder="Enter your new Password">
    </div>
    <button type="submit" class="btn btn-outline-primary">Submit</button>
</form>

Platine/Views/User/EditProfil.cshtml
@model Platine.Database.BusinessObject.User

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center text-white mb-4">Edit Profil Form</h2>
            <div class="row">
                <div class="col-md-10    mx-auto">
                    <span class="anchor" id="formLogin"></span>
                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">Edit Profil : @Session["PlatineLogin"]</h3>
                        </div>
                        <div class="card-body">

                            
                            @if (ViewBag.Error != null)
                            {
                                <div class="alert alert-danger alert-dismissable fade show">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    <strong>@ViewBag.Error</strong>
                                </div>
                            }



                            <form class="form" role="form" autocomplete="off" id="formLogin" action="/User/SubmitEditProfil">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            
                                            <input type="hidden" class="form-control form-control-lg rounded-0" name="Id" value="@Model.Id" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Name</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Name" value="@Model.Name" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">First Name</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="FirstName" value="@Model.FirstName"  required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Birth</label>
                                            <input type="date" class="form-control form-control-lg rounded-0" name="Birth" value="@Model.Birth.ToString("d")"  required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Address</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Address"value="@Model.Address"  required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Mail</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Mail" value="@Model.Mail"  required="" >
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            
                                            <input type="hidden" class="form-control form-control-lg rounded-0" name="Login" value="@Model.Login" required="">
                                        </div>
                                        <div class="form-group">
                                            
                                            <input type="hidden" class="form-control form-control-lg rounded-0" name="Password" value="@Model.Password"  required="" autocomplete="new-password">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Description</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Description" value="@Model.Description"  required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Image</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Image" value="@Model.Image"  required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Phone</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Phone" value="@Model.Phone"   required="">
                                        </div>

                                    </div>
                                </div>
                                <input type="submit" class="btn btn-success btn-lg float-right " value="Edit Profil" />

                            </form>
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>

            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>

Platine/Views/User/ExperiencePage.cshtml
@model IEnumerable<Platine.Database.BusinessObject.Experience>

@{
    ViewBag.Title = "ExperiencePage";
}

<h2>ExperiencePage</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Experience")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Start)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Job)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Enterprise)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Job)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enterprise)
            </td>
           
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Platine/Views/User/Index.cshtml
@model Platine.Database.BusinessObject.User

@{
    ViewBag.Title = "Index";
}

<h2>My Profil</h2>

<div>

    <a href="/User/EditPasswordPage" class="btn btn-outline-info">Edit password</a>
    <a href="/User/EditProfil" class="btn btn-outline-success">Edit profil</a>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Facebook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Facebook)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Github)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Github)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

Platine/Views/User/RegisterPage.cshtml
@{
    ViewBag.Title = "RegisterPage";
}
<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center text-white mb-4">Bootstrap 4 Login Form</h2>
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <span class="anchor" id="formLogin"></span>
                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">Register</h3>
                        </div>
                        <div class="card-body">
                            @{
                                string s = "";
                                if (ViewBag.Message != null)
                                {
                                    s = ViewBag.Message;
                                }

                                if (!s.Equals(""))
                                {
                                    <div class="alert alert-danger alert-dismissable fade show">
                                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                                        <strong>@s</strong>
                                    </div>
                                    //ViewBag.Message = "";
                                }
                            }

                            <form class="form" role="form" autocomplete="off" id="formLogin" action="/User/Register">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="uname1">Name</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Name" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">First Name</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="FirstName" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Birth</label>
                                            <input type="date" class="form-control form-control-lg rounded-0" name="Birth" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Address</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Address" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Mail</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Mail" id="uname1" required="">
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="uname1">Login</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Login" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control form-control-lg rounded-0" name="Password" id="pwd1" required="" autocomplete="new-password">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Description</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Description" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Image</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Image" id="uname1" required="">
                                        </div>
                                        <div class="form-group">
                                            <label for="uname1">Phone</label>
                                            <input type="text" class="form-control form-control-lg rounded-0" name="Phone" id="uname1" required="">
                                        </div>

                                    </div>
                                </div>
                                <input type="submit" class="btn btn-success btn-lg float-right " value="login" />

                            </form>
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>

            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>